import { apiClient } from "./client";
import type { PageSpec } from "../types/common";
import type {
  CategoryDetails,
  CategoryInput,
  CategoryListItem,
  CustomerDetails,
  CustomerInput,
  CustomerListItem,
  ProductDetails,
  ProductInput,
  ProductListItem,
  PurchaseOrderDetails,
  PurchaseOrderInput,
  PurchaseOrderListItem,
  SalesOrderDetails,
  SalesOrderInput,
  SalesOrderListItem,
  ShipmentDetails,
  ShipmentInput,
  ShipmentListItem,
  StockListItem,
  SupplierDetails,
  SupplierInput,
  SupplierListItem,
  WarehouseDetails,
  WarehouseInput,
  WarehouseListItem,
} from "../types/domain";

export const resources = {
  categories: {
    path: "/api/categories",
    search: (baseUrl: string, spec: PageSpec) => apiClient.search<CategoryListItem>(baseUrl, "/api/categories", spec),
    get: (baseUrl: string, id: number) => apiClient.get<CategoryDetails>(baseUrl, `/api/categories/${id}`),
    create: (baseUrl: string, body: CategoryInput) => apiClient.create<CategoryInput, CategoryDetails>(baseUrl, "/api/categories", body),
    update: (baseUrl: string, id: number, body: CategoryInput) => apiClient.update<CategoryInput, CategoryDetails>(baseUrl, `/api/categories/${id}`, body),
    remove: (baseUrl: string, id: number) => apiClient.remove(baseUrl, `/api/categories/${id}`),
  },
  suppliers: {
    path: "/api/suppliers",
    search: (baseUrl: string, spec: PageSpec) => apiClient.search<SupplierListItem>(baseUrl, "/api/suppliers", spec),
    get: (baseUrl: string, id: number) => apiClient.get<SupplierDetails>(baseUrl, `/api/suppliers/${id}`),
    create: (baseUrl: string, body: SupplierInput) => apiClient.create<SupplierInput, SupplierDetails>(baseUrl, "/api/suppliers", body),
    update: (baseUrl: string, id: number, body: SupplierInput) => apiClient.update<SupplierInput, SupplierDetails>(baseUrl, `/api/suppliers/${id}`, body),
    remove: (baseUrl: string, id: number) => apiClient.remove(baseUrl, `/api/suppliers/${id}`),
  },
  customers: {
    path: "/api/customers",
    search: (baseUrl: string, spec: PageSpec) => apiClient.search<CustomerListItem>(baseUrl, "/api/customers", spec),
    get: (baseUrl: string, id: number) => apiClient.get<CustomerDetails>(baseUrl, `/api/customers/${id}`),
    create: (baseUrl: string, body: CustomerInput) => apiClient.create<CustomerInput, CustomerDetails>(baseUrl, "/api/customers", body),
    update: (baseUrl: string, id: number, body: CustomerInput) => apiClient.update<CustomerInput, CustomerDetails>(baseUrl, `/api/customers/${id}`, body),
    remove: (baseUrl: string, id: number) => apiClient.remove(baseUrl, `/api/customers/${id}`),
  },
  warehouses: {
    path: "/api/warehouses",
    search: (baseUrl: string, spec: PageSpec) => apiClient.search<WarehouseListItem>(baseUrl, "/api/warehouses", spec),
    get: (baseUrl: string, id: number) => apiClient.get<WarehouseDetails>(baseUrl, `/api/warehouses/${id}`),
    create: (baseUrl: string, body: WarehouseInput) => apiClient.create<WarehouseInput, WarehouseDetails>(baseUrl, "/api/warehouses", body),
    update: (baseUrl: string, id: number, body: WarehouseInput) => apiClient.update<WarehouseInput, WarehouseDetails>(baseUrl, `/api/warehouses/${id}`, body),
    remove: (baseUrl: string, id: number) => apiClient.remove(baseUrl, `/api/warehouses/${id}`),
  },
  products: {
    path: "/api/products",
    search: (baseUrl: string, spec: PageSpec) => apiClient.search<ProductListItem>(baseUrl, "/api/products", spec),
    get: (baseUrl: string, id: number) => apiClient.get<ProductDetails>(baseUrl, `/api/products/${id}`),
    create: (baseUrl: string, body: ProductInput) => apiClient.create<ProductInput, ProductDetails>(baseUrl, "/api/products", body),
    update: (baseUrl: string, id: number, body: ProductInput) => apiClient.update<ProductInput, ProductDetails>(baseUrl, `/api/products/${id}`, body),
    remove: (baseUrl: string, id: number) => apiClient.remove(baseUrl, `/api/products/${id}`),
  },
  stock: {
    search: (baseUrl: string, spec: PageSpec) => apiClient.search<StockListItem>(baseUrl, "/api/stock-items", spec),
  },
  purchaseOrders: {
    search: (baseUrl: string, spec: PageSpec) => apiClient.search<PurchaseOrderListItem>(baseUrl, "/api/purchase-orders", spec),
    get: (baseUrl: string, id: number) => apiClient.get<PurchaseOrderDetails>(baseUrl, `/api/purchase-orders/${id}`),
    create: (baseUrl: string, body: PurchaseOrderInput) => apiClient.create<PurchaseOrderInput, PurchaseOrderDetails>(baseUrl, "/api/purchase-orders", body),
    update: (baseUrl: string, id: number, body: PurchaseOrderInput) => apiClient.update<PurchaseOrderInput, PurchaseOrderDetails>(baseUrl, `/api/purchase-orders/${id}`, body),
    receive: (baseUrl: string, id: number) => apiClient.action<PurchaseOrderDetails>(baseUrl, `/api/purchase-orders/${id}/receive`),
  },
  salesOrders: {
    search: (baseUrl: string, spec: PageSpec) => apiClient.search<SalesOrderListItem>(baseUrl, "/api/sales-orders", spec),
    get: (baseUrl: string, id: number) => apiClient.get<SalesOrderDetails>(baseUrl, `/api/sales-orders/${id}`),
    create: (baseUrl: string, body: SalesOrderInput) => apiClient.create<SalesOrderInput, SalesOrderDetails>(baseUrl, "/api/sales-orders", body),
    update: (baseUrl: string, id: number, body: SalesOrderInput) => apiClient.update<SalesOrderInput, SalesOrderDetails>(baseUrl, `/api/sales-orders/${id}`, body),
    confirm: (baseUrl: string, id: number) => apiClient.action<SalesOrderDetails>(baseUrl, `/api/sales-orders/${id}/confirm`),
  },
  shipments: {
    search: (baseUrl: string, spec: PageSpec) => apiClient.search<ShipmentListItem>(baseUrl, "/api/shipments", spec),
    get: (baseUrl: string, id: number) => apiClient.get<ShipmentDetails>(baseUrl, `/api/shipments/${id}`),
    create: (baseUrl: string, body: ShipmentInput) => apiClient.create<ShipmentInput, ShipmentDetails>(baseUrl, "/api/shipments", body),
    update: (baseUrl: string, id: number, body: Pick<ShipmentInput, "carrier" | "trackingCode">) =>
      apiClient.update<Pick<ShipmentInput, "carrier" | "trackingCode">, ShipmentDetails>(baseUrl, `/api/shipments/${id}`, body),
    ship: (baseUrl: string, id: number) => apiClient.action<ShipmentDetails>(baseUrl, `/api/shipments/${id}/ship`),
  },
};
